Mission07/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Mission07.Models;

namespace Mission07.Components
{
    // add a cart summary in the top right corner of the screen 
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket cartservice)
        {
            cart = cartservice;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission07/Components/CatViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Mission07.Models;

namespace Mission07.Components
{
    public class CatViewComponent : ViewComponent
    {
        // bring in the IBookProjectRepository and assign to a instance of CatViewComponent
        private IBookProjectRepository repo { get; set; }

        public CatViewComponent (IBookProjectRepository temp)
        {
            repo = temp;
        }

        // query the data and return it in a ViewBag
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookCat"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Mission07/Views/Shared/BookSummary.cshtml
@{
}

@model Book

@* calls on books model to generate a dynamic list of books *@

<div class="card card-outline-primary m-1 p-1">

    <div class="bg-dark text-white p-2">
        <h3>@Model.Title</h3>

        <span class="badge bg-info" style="float: right">
            Price: $@Model.Price
        </span>
    </div>
    <br />
    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification/Category: @Model.Classification/@Model.Category</li>
        <li>Number of Pages: @Model.PageCount</li>
    </ul>

    @* creates a purchase button and carries the book id with it as well as the url to return to *@
    <form method="post" asp-page="/Purchase">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm" style="float: right">Purchase</button>
        </span>
    </form>
</div>

Mission07/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
</head>
<body>
    @* this acts as base html that all cshtml pages will inherit from *@

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand m-lg-2">
                    THE BOOK COLLECTION
                </div>
                @* display cart summary alongside the title *@
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </div>
    </div>

    

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:cat></vc:cat>
        </div>

        <div class="col-9">

            <main role="main" class="pb-3">
                @RenderBody()
            </main>

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>