Mission07/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Mission07.Models
{
    public class Purchase
    {
        // creates the table for Purchases using PurchaseId as the primary key
        [Key]
        [BindNever]
        public int PurchaseId { get; set; }

        [BindNever]
        public ICollection<BasketLineItem> Lines { get; set; }

        // also includes error messages if user doesn't enter anything
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter an Address Line 1")]
        public string AddressLine1 { get; set; }

        public string AddressLine2 { get; set; }

        [Required(ErrorMessage = "Please enter a city")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please enter a state")]
        public string State { get; set; }

        public int Zip { get; set; }

        [Required(ErrorMessage = "Please enter a country")]
        public string Country { get; set; }

        // add a shipped true/false
        [BindNever]
        public bool Shipped { get; set; }
    }
}

Mission07/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission07.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mission07.Controllers
{
    public class PurchaseController : Controller
    {
        // initialize the IPurchaseRepository and Basket
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }

        public PurchaseController(IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        // get method for a new purchase
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        // post method for the purchase
        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            // throw error if they have no items in the cart
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            // if the cart is valid, save the purchase to the purchases table and
            // redirect them to the PurchaseCompleted page
            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            // else take them to the home page
            else
            {
                return View();
            }
        }
    }
}

Mission07/Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission07.Infrastructure;
using Mission07.Models;

namespace Mission07.Pages
{
    public class PurchaseModel : PageModel
    {
        // bring in the IBookProjectRepository and assign it to a variable to be
        // used as an instance in this class
        private IBookProjectRepository repo { get; set; }

        public Basket basket { get; set; }

        public string ReturnUrl { get; set; }

        public PurchaseModel (IBookProjectRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public void OnGet(string returnUrl)
        {
            // take them back to the returnUrl if exists, else take them to the homepage
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            // add the book to the cart via the book Id
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            // redirect back to the ReturnUrl
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Mission07/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission07.Pages
{
    // simple model related to the PurchaseCompleted Razor Page
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission07/Pages/Purchase.cshtml
@page
@model Mission07.Pages.PurchaseModel
@{
}

<h2>Your Basket</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>Item</td>
            <td>Quantity</td>
            <td>Total</td>
            <td>Subtotal</td>
        </tr>
    </thead>

    @* display the title, quantity, total, and price for each book *@
    <tbody>
        @foreach(var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>1</td>
                <td>$@(i.Quantity * i.Book.Price)</td>

                @* add a delete button *@
                <td class="text-cente">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="BookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    @* calculate the price of the book by referencing the Calculate Total function *@
    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    @* add a purchase button along witht he continue shopping button *@
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Purchase" asp-action="Checkout">Checkout</a>
</div>

Mission07/Pages/PurchaseCompleted.cshtml
@page
@model Mission07.Pages.PurchaseCompletedModel
@{
}

@* short purchase confirmation screen with a button to return home *@
<div class="text-center">
    <h2>Thank you for your purchase! You will receive your books shortly.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Mission07/Pages/_PurchaseLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @* creates a layout for the page you visit when you purchase a book *@
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">
            THE BOOK COLLECTION
        </span>
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>